In [3]:
from tensorflow.keras.preprocessing.text import one_hot


In [4]:
### Sentences
sent= [
    'the glass of milk',
    'the glass of juice',
    'here are my sentences',
    'with which we will play with',
    'for preprocessing and word to vector'
]
sent

['the glass of milk',
 'the glass of juice',
 'here are my sentences',
 'with which we will play with',
 'for preprocessing and word to vector']

In [5]:
## Define the vocabulary size
voc_size = 10000

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'here are my sentences',
 'with which we will play with',
 'for preprocessing and word to vector']

In [7]:
### One Hot Representation
one_hot_repr = [one_hot(words, voc_size)for words in sent]
one_hot_repr


[[5309, 8506, 6981, 2162],
 [5309, 8506, 6981, 680],
 [1883, 3479, 6627, 3819],
 [3434, 2376, 9526, 6249, 2339, 3434],
 [9006, 2947, 8774, 1464, 8809, 1748]]

In [8]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
#from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [9]:
import numpy as np

In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre',maxlen=sent_length)

In [11]:
print(embedded_docs)

[[   0    0    0    0 5309 8506 6981 2162]
 [   0    0    0    0 5309 8506 6981  680]
 [   0    0    0    0 1883 3479 6627 3819]
 [   0    0 3434 2376 9526 6249 2339 3434]
 [   0    0 9006 2947 8774 1464 8809 1748]]


In [12]:
## feature representation
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\Gen_AI_practice\Simple_RNN_word2vec_Movie_Review\movie_review\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [14]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [15]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step


array([[[ 2.8705906e-02, -2.2964228e-02, -3.0949688e-02, -6.5616257e-03,
         -1.5144125e-03, -4.4671070e-02, -7.1303733e-03,  4.3022338e-02,
          1.7652664e-02, -8.2070455e-03],
        [ 2.8705906e-02, -2.2964228e-02, -3.0949688e-02, -6.5616257e-03,
         -1.5144125e-03, -4.4671070e-02, -7.1303733e-03,  4.3022338e-02,
          1.7652664e-02, -8.2070455e-03],
        [ 2.8705906e-02, -2.2964228e-02, -3.0949688e-02, -6.5616257e-03,
         -1.5144125e-03, -4.4671070e-02, -7.1303733e-03,  4.3022338e-02,
          1.7652664e-02, -8.2070455e-03],
        [ 2.8705906e-02, -2.2964228e-02, -3.0949688e-02, -6.5616257e-03,
         -1.5144125e-03, -4.4671070e-02, -7.1303733e-03,  4.3022338e-02,
          1.7652664e-02, -8.2070455e-03],
        [ 3.8394704e-03,  1.8932734e-02, -1.7125476e-02, -2.8917396e-02,
         -2.9355193e-02, -9.4665065e-03,  2.2038333e-03,  4.8985090e-02,
         -3.4560729e-02,  6.1716922e-03],
        [ 4.6782378e-02,  1.7640702e-03, -3.5641015e-02,  2.

In [16]:
embedded_docs[0]

array([   0,    0,    0,    0, 5309, 8506, 6981, 2162], dtype=int32)

In [24]:
input_sample = np.expand_dims(embedded_docs[0], axis=0)
print(input_sample.shape)

(1, 8)


In [25]:
print(np.shape(embedded_docs[0]))

(8,)


In [34]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


array([[[ 2.8705906e-02, -2.2964228e-02, -3.0949688e-02, -6.5616257e-03,
         -1.5144125e-03, -4.4671070e-02, -7.1303733e-03,  4.3022338e-02,
          1.7652664e-02, -8.2070455e-03],
        [ 2.8705906e-02, -2.2964228e-02, -3.0949688e-02, -6.5616257e-03,
         -1.5144125e-03, -4.4671070e-02, -7.1303733e-03,  4.3022338e-02,
          1.7652664e-02, -8.2070455e-03],
        [ 2.8705906e-02, -2.2964228e-02, -3.0949688e-02, -6.5616257e-03,
         -1.5144125e-03, -4.4671070e-02, -7.1303733e-03,  4.3022338e-02,
          1.7652664e-02, -8.2070455e-03],
        [ 2.8705906e-02, -2.2964228e-02, -3.0949688e-02, -6.5616257e-03,
         -1.5144125e-03, -4.4671070e-02, -7.1303733e-03,  4.3022338e-02,
          1.7652664e-02, -8.2070455e-03],
        [ 3.8394704e-03,  1.8932734e-02, -1.7125476e-02, -2.8917396e-02,
         -2.9355193e-02, -9.4665065e-03,  2.2038333e-03,  4.8985090e-02,
         -3.4560729e-02,  6.1716922e-03],
        [ 4.6782378e-02,  1.7640702e-03, -3.5641015e-02,  2.